TDD project
Alhajideen/TDD-project pull request #1
Opened 2023-01-05 23:37 UTC by Kelvin-Ben

## TDD project
- In this project, we wrote tests for methods before initializing the class and methods.
- The tests failed with the uninitialized method and class error.
- We also wrote the main class Solver and added three methods as required
- After writing every method as required we ran the test again and the passed

![TDD](https://user-images.githubusercontent.com/85459676/210900330-43f230be-8d5b-4368-bd68-ccd99c73888f.png)

2023-01-05 23:54 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @Kelvin-Ben, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters passing
✔️ Correct Gitflow
✔️ Professional Readme

## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 23:54 UTC, sja-thedude commented on README.md
>    <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] Kindly remove the microverse logo as its your own project.

2023-01-05 23:54 UTC, sja-thedude commented on README.md
> +- [NOT AVAILABLE AT THE MOMENT]()
- [ ] Kindly remove the Live Demo as its not required.

2023-01-06 00:07 UTC, Olamarx approved these changes
Hi @Kelvin-Ben, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
## Highlights
- Linter passed ✔️
- GitHub and Git flow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 00:23 UTC, Kelvin-Ben commented
Thank you @Olamarx for the review

2023-01-06 00:23 UTC, merged